### ISSUE TITLE
Depuplicate names in sources/auctions/bidders.csv

### ISSUE THREAD

**Issue by jrnold** [jrnold/civil_war_era_findata#3]
Deduplicate the individuals in the sources/auctions/bidders.csv, which has the names of bidders across several auctions.  This should probably require adding the following columns.
- canonical name (to be used to indicate the same entities across rows). I don't have a good idea of how to structure this. Use your judgement.
- corporation name
- first name. Some of these may be abbreviated, e.g. Thos. for Thomas. Expand these using the list of abbreviations [here](https://en.wiktionary.org/wiki/Appendix:Abbreviations_for_English_given_names)
- last name
- middle name
- title (e.g. trustee, secretary, president)
- beneficiary (e.g. "on behalf of", "for" etc.)

I already have a variable `institutional` that indicates whether I thought it seemed to be a corporation. You should be able to deduplicate by splitting off the titles or beneificiary parts with regexes, then using humaniform on non-institutions. Then sort, and manually identify clusters. Of course, if you can find a better way, go for it. 

Some of the issues with people appearing to act on their own and as agents of others may be hard to figure out. If that's the case, mark them and I'll look over them after you are done.

**Comment by weszuidema** [comment]
@jrnold Check this out and see if it needs further tweaking. Changes in branch issue_3. Corporation_name and canonical_name can be combined if you like, I was just following your directions for what should be in the file.
